### PR TITLE
fix(build): removed arrow funcion from carbon-icons.js

### LINKED ISSUE #60: Latest version of carbon-icons contains es6 code
I have a project that has a dependency on carbon-icons version 6.3.0.

There is a file called carbon-icons.js in the dist folder that contains ES6 code and is currently breaking the unit tests of my project.

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token '>'
  at tests/ui/test_index.js:49717 <- webpack:///~/carbon-icons/dist/carbon-icons.js:2649:0
```

This seems to be caused by the following arrow function (code from node_module folder)
```js
function camelCaseFromHyphnated(s) {
  return s.replace(/-+([A-z])/g, (match, token) => token.toUpperCase());
}
```

### PR DESCRIPTION
**Pull request by Licen-it**
fixes #60 

Removed transpilers dependency replacing an arrow function with a normal function

### CODE REVIEW

**Comment by asudoh** [comment]
@Licen-it Thank you for trying to make a contribution! According to http://node.green/#ES2015-functions-arrow-functions arrow functions are supported by Node4 which is pretty old. Given the code never runs on browser, the code you are trying to fix does *not *create a transpiler dependency. Feel free to speak up if I’m missing anything. Thanks!

**Comment by Licen-it** [comment]
@asudoh not sure why you are saying that carbon-icons.js is not running in the browser, as the error mentioned in #60 is happening in my project UI. Followed the error through `carbon-components` which is importing this project and I'm importing some components from carbon.

**Comment by asudoh** [comment]
@Licen-it Thank you for elaborating your concern. The code you made the fix to is *not* part of `carbon-icons.js` - It instead is the file that creates `carbon-icons.js`. I suspect you hit the issue fixed by https://github.com/carbon-design-system/carbon-icons/pull/58.

**Comment by Licen-it** [comment]
@asudoh I know that the file i changes is the one creating `carbon-icons.js`. The error I'm getting if you check the logs i posted in #60 is pointing to `carbon-icons.js` and in my `node_module` folder i have that file with an arrow function at the bottom, because the file creating it is adding an arrow function. I'm aware about #58 as it was fixing the issue a colleague reported, but this is same error but different cause.

**Comment by asudoh** [comment]
@Licen-it Sorry I totally missed that the code is in the backtick!

**Pull request merged**
